package com.siddhesh.yepl.utils

class Keys {
    companion object {
        const val KEY_TERM = "term"
        const val KEY_LOCATION = "location"
        const val KEY_RADIUS = "radius"
        const val KEY_SORT_BY = "sort_by"
        const val KEY_LIMIT = "limit"
        const val KEY_AUTHORIZATION = "Authorization"
        const val KEY_BUSINESSES = "businesses"
        const val KEY_TOTAL = "total"
        const val KEY_ID = "id"
        const val KEY_ALIAS = "alias"
        const val KEY_NAME = "name"
        const val KEY_IMAGE_URL = "image_url"
        const val KEY_IS_CLOSED = "is_closed"
        const val KEY_URL = "url"
        const val KEY_REVIEW_COUNT = "review_count"
        const val KEY_CATEGORIES = "categories"
        const val KEY_TITLE = "title"
        const val KEY_RATING = "rating"
        const val KEY_COORDINATES = "coordinates"
        const val KEY_LATITUDE = "latitude"
        const val KEY_LONGITUDE = "longitude"
        const val KEY_TRANSACTIONS = "transactions"
        const val KEY_PRICE = "price"
        const val KEY_ADDRESS1 = "address1"
        const val KEY_ADDRESS2 = "address2"
        const val KEY_ADDRESS3 = "address3"
        const val KEY_CITY = "city"
        const val KEY_ZIP_CODE = "zip_code"
        const val KEY_COUNTRY = "country"
        const val KEY_STATE = "STATE"
        const val KEY_DISPLAY_ADDRESS = "display_address"
        const val KEY_PHONE = "phone"
        const val KEY_DISPLAY_PHONE = "display_phone"
        const val KEY_DISTANCE = "distance"
        const val KEY_OFFSET = "offset"
        const val KEY_CODE = "code"
        const val KEY_DESCRIPTION = "description"
        const val KEY_ERROR = "error"
    }
}